# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_int_lt <- function(x, value) {
    .Call(`_timeplyr_any_int_lt`, x, value)
}

any_num_lt <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_lt`, x, value, tol)
}

any_int_lte <- function(x, value) {
    .Call(`_timeplyr_any_int_lte`, x, value)
}

any_num_lte <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_lte`, x, value, tol)
}

any_int_gt <- function(x, value) {
    .Call(`_timeplyr_any_int_gt`, x, value)
}

any_num_gt <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_gt`, x, value, tol)
}

any_int_gte <- function(x, value) {
    .Call(`_timeplyr_any_int_gte`, x, value)
}

any_num_gte <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_gte`, x, value, tol)
}

any_int_equal <- function(x, value) {
    .Call(`_timeplyr_any_int_equal`, x, value)
}

any_num_equal <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_equal`, x, value, tol)
}

is_whole_num <- function(x, tol) {
    .Call(`_timeplyr_is_whole_num`, x, tol)
}

roll_apply_max_fast <- function(x, before, after) {
    .Call(`_timeplyr_roll_apply_max_fast`, x, before, after)
}

roll_apply_max <- function(x, before, after, na_rm, partial) {
    .Call(`_timeplyr_roll_apply_max`, x, before, after, na_rm, partial)
}

before_sequence <- function(size, k) {
    .Call(`_timeplyr_before_sequence`, size, k)
}

after_sequence <- function(size, k) {
    .Call(`_timeplyr_after_sequence`, size, k)
}

window_sequence <- function(size, k, partial, ascending) {
    .Call(`_timeplyr_window_sequence`, size, k, partial, ascending)
}

lag_sequence <- function(size, k) {
    .Call(`_timeplyr_lag_sequence`, size, k)
}

lead_sequence <- function(size, k) {
    .Call(`_timeplyr_lead_sequence`, size, k)
}

roll_int_threshold <- function(x, threshold = 1L, switch_on_boundary = TRUE) {
    .Call(`_timeplyr_roll_int_threshold`, x, threshold, switch_on_boundary)
}

roll_time_threshold <- function(x, threshold = 1, switch_on_boundary = TRUE) {
    .Call(`_timeplyr_roll_time_threshold`, x, threshold, switch_on_boundary)
}

