# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_time_threshold <- function(x, threshold = 1, switch_on_boundary = TRUE, tol = 0) {
    .Call(`_timeplyr_roll_time_threshold`, x, threshold, switch_on_boundary, tol)
}

