# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_int_lt <- function(x, value) {
    .Call(`_timeplyr_any_int_lt`, x, value)
}

any_num_lt <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_lt`, x, value, tol)
}

any_int_lte <- function(x, value) {
    .Call(`_timeplyr_any_int_lte`, x, value)
}

any_num_lte <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_lte`, x, value, tol)
}

any_int_gt <- function(x, value) {
    .Call(`_timeplyr_any_int_gt`, x, value)
}

any_num_gt <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_gt`, x, value, tol)
}

any_int_gte <- function(x, value) {
    .Call(`_timeplyr_any_int_gte`, x, value)
}

any_num_gte <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_gte`, x, value, tol)
}

any_int_equal <- function(x, value) {
    .Call(`_timeplyr_any_int_equal`, x, value)
}

any_num_equal <- function(x, value, tol) {
    .Call(`_timeplyr_any_num_equal`, x, value, tol)
}

is_whole_num <- function(x, tol) {
    .Call(`_timeplyr_is_whole_num`, x, tol)
}

roll_int_threshold <- function(x, threshold = 1L, switch_on_boundary = TRUE) {
    .Call(`_timeplyr_roll_int_threshold`, x, threshold, switch_on_boundary)
}

roll_time_threshold <- function(x, threshold = 1, switch_on_boundary = TRUE) {
    .Call(`_timeplyr_roll_time_threshold`, x, threshold, switch_on_boundary)
}

